神社選択のボタンを改良しました
shun-harutaro/nft-nenga pull request #38
Opened 2024-12-06 02:05 UTC by iamkawaryo

## 概要

## 関連タスク
Close #  (required)

## やったこと

## やらないこと

## レビュー事項
-

## 補足 参考情報

2024-12-06 05:19 UTC, shun-harutaro requested changes
CSSいい感じー少しだけ修正よろしくー

2024-12-09 13:08 UTC, iamkawaryo commented on frontend/src/views/Location.vue
> -import apiAxios from "@/plugin/axios";
了解です

2024-12-09 13:09 UTC, iamkawaryo commented on nft-nenga
これ俺も謎のファイルだったんよね
消しときます

2024-12-10 05:26 UTC, shun-harutaro approved these changes

2024-12-10 08:03 UTC, merged